// ===== 通用工具 =====
const key = (q, r) => `${q},${r}`;
const other = side => side === "player" ? "enemy" : "player";
const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
const offsetToAxial = (col, row) => ({ q: col, r: row - Math.floor(col / 2) });
function getMapCoordinates(map = CONFIG.map) {
  const cells = [];
  for (let col = 0; col < map.cols; col++) {
    for (let row = 0; row < map.rows; row++) {
      cells.push(map.shape === "offsetRectangle" ? offsetToAxial(col, row) : { q: col, r: row });
    }
  }
  return cells;
}

// ===== 六边形工具 HexUtils =====
const HexUtils = {
  size: CONFIG.map.hexSize,
  axialToPixel(q, r) { return { x: this.size * 1.5 * q, y: this.size * (Math.sqrt(3) * r + Math.sqrt(3) / 2 * q) }; },
  pixelToAxialRaw(x, y) { return { q: (2 / 3 * x) / this.size, r: (-1 / 3 * x + Math.sqrt(3) / 3 * y) / this.size }; },
  round(q, r) { const s = -q - r; let rq = Math.round(q), rr = Math.round(r), rs = Math.round(s); const qd = Math.abs(rq - q), rd = Math.abs(rr - r), sd = Math.abs(rs - s); if (qd > rd && qd > sd) rq = -rr - rs; else if (rd > sd) rr = -rq - rs; return { q: rq, r: rr }; },
  directions: [{ q: 1, r: 0 }, { q: 1, r: -1 }, { q: 0, r: -1 }, { q: -1, r: 0 }, { q: -1, r: 1 }, { q: 0, r: 1 }],
  neighbors(q, r) { return this.directions.map(d => ({ q: q + d.q, r: r + d.r })); },
  distance(q1, r1, q2, r2) { return (Math.abs(q1 - q2) + Math.abs(q1 + r1 - q2 - r2) + Math.abs(r1 - r2)) / 2; },
  drawHex(g, size, fill, line, width = 2) { g.beginFill(fill); g.lineStyle(width, line); g.moveTo(size, 0); for (let i = 1; i < 6; i++) { const a = Math.PI / 3 * i; g.lineTo(size * Math.cos(a), size * Math.sin(a)); } g.closePath(); g.endFill(); },
};

// ===== 寻路 PathFinder =====
class PathFinder {
  constructor(game) { this.game = game; }
  find(start, goal) {
    const sk = key(start.q, start.r), open = [{ ...start, g: 0, f: HexUtils.distance(start.q, start.r, goal.q, goal.r) }], came = new Map(), cost = new Map([[sk, 0]]); let best = open[0], bestH = open[0].f;
    while (open.length) { open.sort((a, b) => a.f - b.f); const cur = open.shift(), ck = key(cur.q, cur.r), h = HexUtils.distance(cur.q, cur.r, goal.q, goal.r); if (h < bestH) { best = cur; bestH = h; } if (cur.q === goal.q && cur.r === goal.r) { best = cur; break; } for (const n of HexUtils.neighbors(cur.q, cur.r)) { const tile = this.game.tiles.get(key(n.q, n.r)); if (!tile || !tile.revealed) continue; const nk = key(n.q, n.r), ng = cur.g + 1; if (ng < (cost.get(nk) ?? Infinity)) { cost.set(nk, ng); came.set(nk, ck); open.push({ ...n, g: ng, f: ng + HexUtils.distance(n.q, n.r, goal.q, goal.r) }); } } }
    const path = []; let cursor = key(best.q, best.r); if (cursor === sk) return path; while (cursor !== sk && came.has(cursor)) { const [q, r] = cursor.split(",").map(Number); path.unshift({ q, r }); cursor = came.get(cursor); } return path;
  }
}

// ===== 游戏状态 Game =====
class Game {
  constructor(renderer, ui) { this.renderer = renderer; this.ui = ui; this.pathFinder = new PathFinder(this); this.currentMapId = CONFIG.map.id; this.reset(); }
  selectMap(mapId) { const map = CONFIG.maps[mapId]; if (!map) throw new Error(`未知地图：${mapId}`); validateMapConfig(map, mapId); CONFIG.map = map; HexUtils.size = map.hexSize; this.currentMapId = mapId; this.reset(); }
  reset() {
    this.renderer.reset(); this.phase = "prepare"; this.prepareLeft = CONFIG.battle.prepareTime; this.timeLeft = CONFIG.battle.duration; this.mapVersion = 1; this.nextId = 1; this.tiles = new Map(); this.buildings = []; this.units = []; this.selectedTile = null; this.aiClock = 0;
    this.sides = {}; for (const side of SIDES) this.sides[side] = { gold: CONFIG.economy.startGold, goldEarned: 0, unitKills: 0, buildingsDestroyed: 0, captures: 0, generalRevive: null };
    for (const { q, r } of getMapCoordinates()) this.tiles.set(key(q, r), { q, r, revealed: false, owner: "none", building: null, capture: { side: null, progress: 0 } });
    const layout = CONFIG.map.initialLayout;
    this.setupSide("player", layout.playerCity, layout.playerTerritory); this.setupSide("enemy", layout.enemyCity, layout.enemyTerritory); this.renderer.buildMap(this); this.ui.reset(); this.ui.update(this); this.renderer.resize();
  }
  setupSide(side, cityPos, territory) { for (const p of [cityPos, ...territory]) { const t = this.tile(p.q, p.r); t.revealed = true; t.owner = side; } this.createBuilding("main_city", side, this.tile(cityPos.q, cityPos.r)); }
  tile(q, r) { return this.tiles.get(key(q, r)); }
  update(dt) { if (this.phase === "prepare") { this.prepareLeft -= dt; if (this.prepareLeft <= 0) { this.phase = "battle"; this.prepareLeft = 0; this.ui.toast("开战！"); } return; } if (this.phase !== "battle") return; this.timeLeft -= dt; if (this.timeLeft <= 0) { this.timeLeft = 0; this.finishByTime(); return; } this.updateEconomy(dt); this.updateBuildings(dt); this.checkCityVictory(); if (this.phase !== "battle") return; this.updateUnits(dt); this.checkCityVictory(); if (this.phase !== "battle") return; this.updateCaptures(dt); this.updateRevives(dt); this.updateAI(dt); this.cleanup(); }
  updateEconomy(dt) { for (const side of SIDES) { const mines = this.buildings.filter(b => !b.dead && b.side === side && b.type === "gold_mine").length; this.earn(side, (CONFIG.economy.baseIncome + mines * CONFIG.economy.mineIncome) * dt); } }
  earn(side, amount) { const st = this.sides[side], actual = Math.min(amount, CONFIG.economy.goldCap - st.gold); st.gold += actual; st.goldEarned += Math.max(0, actual); }
  spend(side, amount) { if (this.sides[side].gold + 1e-6 < amount) return false; this.sides[side].gold -= amount; return true; }
  reveal(tile, side) { if (this.phase !== "battle" || tile.revealed) return false; const adjacent = HexUtils.neighbors(tile.q, tile.r).some(p => { const t = this.tile(p.q, p.r); return t && t.revealed && t.owner === side; }); if (!adjacent || !this.spend(side, CONFIG.reveal.normalCost)) return false; tile.revealed = true; tile.owner = side; const result = this.rollReveal(); if (result === "gold_reward") this.earn(side, CONFIG.reveal.goldReward); else if (result !== "empty") { const type = result === "random_barracks" ? BARRACKS[Math.floor(Math.random() * BARRACKS.length)] : result; this.createBuilding(type, side, tile); } this.mapVersion++; this.renderer.markMapDirty(); if (side === "player") this.ui.toast(result === "gold_reward" ? "发现 50 金币！" : result === "empty" ? "发现一块空地" : `发现${tile.building?.name || "建筑"}！`); return true; }
  rollReveal() { let n = Math.random(); for (const [type, rate] of Object.entries(CONFIG.revealRates.normal)) { n -= rate; if (n <= 0) return type; } return "empty"; }
  build(tile, type, side) { const cfg = CONFIG.buildings[type]; if (this.phase !== "battle" || !cfg || cfg.cost == null || !tile.revealed || tile.owner !== side || tile.building) return false; if (!this.spend(side, cfg.cost)) return false; this.createBuilding(type, side, tile); this.mapVersion++; this.renderer.markMapDirty(); return true; }
  createBuilding(type, side, tile) { const cfg = CONFIG.buildings[type], b = { id: this.nextId++, kind: "building", type, side, tile, name: cfg.name, hp: cfg.hp, maxHp: cfg.hp, cooldown: cfg.spawnInterval ?? 0, dead: false, display: null }; tile.building = b; this.buildings.push(b); if (type === "general_camp") this.ensureGeneral(side); return b; }
  createUnit(type, side, tile, isGeneral = false) { if (!isGeneral && this.units.filter(u => !u.dead && u.side === side && !u.isGeneral).length >= CONFIG.battle.maxUnitsPerSide) return null; const cfg = isGeneral ? CONFIG.general.guanYu : CONFIG.units[type], p = HexUtils.axialToPixel(tile.q, tile.r), u = { id: this.nextId++, kind: "unit", type, isGeneral, side, name: cfg.name, hp: cfg.hp, maxHp: cfg.hp, atk: cfg.atk, speed: cfg.speed, range: cfg.range, atkInterval: cfg.atkInterval, cooldown: 0, skillClock: isGeneral ? 0 : null, x: p.x, y: p.y, path: [], pathIndex: 0, pathVersion: 0, dead: false, display: null }; this.units.push(u); return u; }
  ensureGeneral(side) { if (this.units.some(u => !u.dead && u.side === side && u.isGeneral) || this.sides[side].generalRevive > 0) return; const camp = this.buildings.find(b => !b.dead && b.side === side && b.type === "general_camp"); if (camp) { this.sides[side].generalRevive = null; this.createUnit("guanYu", side, camp.tile, true); } }
  updateBuildings(dt) { for (const b of this.buildings) { if (b.dead) continue; const cfg = CONFIG.buildings[b.type]; if (b.type.startsWith("barracks_")) { b.cooldown -= dt; if (b.cooldown <= 0) { const u = this.createUnit(cfg.unitType, b.side, b.tile); if (u) b.cooldown += cfg.spawnInterval; } } else if (b.type === "tower_arrow" || b.type === "tower_cannon") { b.cooldown -= dt; const targets = this.units.filter(u => !u.dead && u.side !== b.side && this.distanceToTile(u, b.tile) <= cfg.range).sort((a, c) => this.distanceToTile(a, b.tile) - this.distanceToTile(c, b.tile)); if (targets.length && b.cooldown <= 0) { b.cooldown = cfg.atkInterval; if (b.type === "tower_arrow") { this.damage(targets[0], cfg.atk, b); this.renderer.effectLine(b.tile, targets[0], 0xe9dc86); } else { for (const u of this.units) if (!u.dead && u.side !== b.side && this.distanceEntities(u, targets[0]) <= cfg.aoeRadius) this.damage(u, cfg.atk, b); this.renderer.effectRing(targets[0].x, targets[0].y, cfg.aoeRadius, 0xf4a942); } } } } }
  updateUnits(dt) { for (const u of this.units) { if (u.dead) continue; u.cooldown -= dt; if (u.isGeneral) u.skillClock -= dt; if (u.isGeneral && u.skillClock <= 0 && this.units.some(v => !v.dead && v.side !== u.side && this.distanceEntities(u, v) <= CONFIG.general.guanYu.skill.range)) { u.skillClock = CONFIG.general.guanYu.skill.cooldown; for (const v of this.units) if (!v.dead && v.side !== u.side && this.distanceEntities(u, v) <= CONFIG.general.guanYu.skill.range) this.damage(v, CONFIG.general.guanYu.skill.damage, u); this.renderer.effectRing(u.x, u.y, CONFIG.general.guanYu.skill.range, 0xf6d365); } const target = this.chooseTarget(u); if (target) { if (u.cooldown <= 0) { u.cooldown = u.atkInterval; let amount = u.atk; if (!u.isGeneral && target.kind === "unit" && !target.isGeneral) amount *= this.counterMultiplier(u, target); this.damage(target, amount, u); this.renderer.effectLine(u, target, u.side === "player" ? 0x77e6b3 : 0xff7769); } continue; } const here = this.unitTile(u); if (here && this.canCapture(here, u.side) && this.distanceToTile(u, here) <= CONFIG.battle.captureRadius) continue; this.moveUnit(u, dt); } }
  chooseTarget(u) { const candidates = []; for (const v of this.units) if (!v.dead && v.side !== u.side) { const d = this.distanceEntities(u, v); if (d <= u.range) candidates.push({ e: v, d, p: 0 }); } for (const b of this.buildings) if (!b.dead && b.side !== u.side) { const d = this.distanceToTile(u, b.tile); if (d <= u.range) candidates.push({ e: b, d, p: b.type === "main_city" ? 2 : 1 }); } candidates.sort((a, b) => a.p - b.p || a.d - b.d || a.e.hp - b.e.hp || a.e.id - b.e.id); return candidates[0]?.e || null; }
  counterMultiplier(a, t) { if (CONFIG.units[a.type]?.counters === t.type) return 1.5; if (CONFIG.units[t.type]?.counters === a.type) return 0.75; return 1; }
  moveUnit(u, dt) { const goal = this.city(other(u.side))?.tile, start = this.unitTile(u); if (!goal || !start) return; if (u.pathVersion !== this.mapVersion) { u.path = this.pathFinder.find(start, goal); u.pathIndex = 0; u.pathVersion = this.mapVersion; } const node = u.path[u.pathIndex]; if (!node) return; const p = HexUtils.axialToPixel(node.q, node.r), dx = p.x - u.x, dy = p.y - u.y, dist = Math.hypot(dx, dy), step = u.speed * Math.sqrt(3) * HexUtils.size * dt; if (dist <= step) { u.x = p.x; u.y = p.y; u.pathIndex++; } else { u.x += dx / dist * step; u.y += dy / dist * step; } }
  updateCaptures(dt) { let changed = false; for (const tile of this.tiles.values()) { if (!tile.revealed || tile.building) { if (tile.capture.progress) changed = true; tile.capture.side = null; tile.capture.progress = 0; continue; } const present = { player: false, enemy: false }; for (const u of this.units) if (!u.dead && this.distanceToTile(u, tile) <= CONFIG.battle.captureRadius) present[u.side] = true; if (present.player && present.enemy) continue; const side = present.player ? "player" : present.enemy ? "enemy" : null; if (!side || side === tile.owner) { if (tile.capture.progress) changed = true; tile.capture.side = null; tile.capture.progress = 0; continue; } if (tile.capture.side !== side) { tile.capture.side = side; tile.capture.progress = 0; } tile.capture.progress += dt; changed = true; if (tile.capture.progress >= CONFIG.battle.captureTime) { tile.owner = side; tile.capture.side = null; tile.capture.progress = 0; this.sides[side].captures++; this.mapVersion++; } } if (changed) this.renderer.markMapDirty(); }
  updateRevives(dt) { for (const side of SIDES) if (this.sides[side].generalRevive != null) { this.sides[side].generalRevive -= dt; if (this.sides[side].generalRevive <= 0) this.ensureGeneral(side); } }
  updateAI(dt) { this.aiClock -= dt; if (this.aiClock > 0) return; this.aiClock = CONFIG.ai.decisionInterval; const side = "enemy", st = this.sides[side], empty = this.emptyTiles(side), mines = this.countBuildings(side, "gold_mine"), barracks = this.buildings.filter(b => !b.dead && b.side === side && BARRACKS.includes(b.type)).length, towers = this.countBuildings(side, "tower_arrow"); if (!mines && empty.length) { if (st.gold >= 50) this.build(this.pickAI(empty), "gold_mine", side); return; } if (!barracks && empty.length) { if (st.gold >= 80) this.build(this.pickAI(empty), BARRACKS[Math.floor(Math.random() * BARRACKS.length)], side); return; } const city = this.city(side), danger = this.units.some(u => !u.dead && u.side !== side && this.distanceToTile(u, city.tile) <= CONFIG.ai.emergencyCityRange), front = this.frontTiles(side); if (danger && st.gold >= 60 && front.length && towers < CONFIG.ai.maxArrowTowers) { this.build(this.pickAI(front), "tower_arrow", side); return; } if (mines < CONFIG.ai.maxMines && st.gold >= 75 && empty.length) { this.build(this.pickAI(empty), "gold_mine", side); return; } if (barracks < CONFIG.ai.maxBarracks && st.gold >= 105 && empty.length) { this.build(this.pickAI(empty), BARRACKS[Math.floor(Math.random() * BARRACKS.length)], side); return; } if (towers < CONFIG.ai.maxArrowTowers && st.gold >= 85 && front.length) { this.build(this.pickAI(front), "tower_arrow", side); return; } const candidates = [...this.tiles.values()].filter(t => !t.revealed && HexUtils.neighbors(t.q, t.r).some(p => this.tile(p.q, p.r)?.owner === side)); if (st.gold >= 25 && candidates.length) { const target = CONFIG.map.initialLayout.playerCity; candidates.sort((a, b) => HexUtils.distance(a.q, a.r, target.q, target.r) - HexUtils.distance(b.q, b.r, target.q, target.r) || this.unknownNeighbors(b) - this.unknownNeighbors(a)); this.reveal(candidates[0], side); } }
  pickAI(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
  unknownNeighbors(t) { return HexUtils.neighbors(t.q, t.r).filter(p => { const n = this.tile(p.q, p.r); return n && !n.revealed; }).length; }
  emptyTiles(side) { return [...this.tiles.values()].filter(t => t.revealed && t.owner === side && !t.building); }
  frontTiles(side) { const target = this.city(other(side)).tile, arr = this.emptyTiles(side); return arr.sort((a, b) => HexUtils.distance(a.q, a.r, target.q, target.r) - HexUtils.distance(b.q, b.r, target.q, target.r)).slice(0, 3); }
  countBuildings(side, type) { return this.buildings.filter(b => !b.dead && b.side === side && b.type === type).length; }
  damage(target, amount, source) { if (target.dead || this.phase !== "battle") return; target.hp -= amount; if (target.hp > 0) return; target.hp = 0; target.dead = true; if (target.kind === "unit") { if (source?.side) this.sides[source.side].unitKills++; if (target.isGeneral) this.sides[target.side].generalRevive = CONFIG.general.guanYu.reviveTime; } else { target.tile.building = null; if (target.type === "main_city") return; if (source?.side) this.sides[source.side].buildingsDestroyed++; this.mapVersion++; this.renderer.markMapDirty(); } }
  checkCityVictory() { const p = this.city("player"), e = this.city("enemy"); if ((!p || p.dead) && (!e || e.dead)) this.finish(null, "双方主城同时被摧毁"); else if (!p || p.dead) this.finish("enemy", "我方主城被摧毁"); else if (!e || e.dead) this.finish("player", "敌方主城被摧毁"); }
  finishByTime() { const territory = s => this.territory(s), buildingHp = s => this.buildings.filter(b => !b.dead && b.side === s).reduce((n, b) => n + b.hp, 0), unitHp = s => this.units.filter(u => !u.dead && u.side === s).reduce((n, u) => n + u.hp, 0); let winner = null, reason = "双方完全持平"; for (const [fn, label] of [[territory, "领地数量"], [buildingHp, "建筑生命"], [unitHp, "单位生命"]]) { const p = fn("player"), e = fn("enemy"); if (p !== e) { winner = p > e ? "player" : "enemy"; reason = `${label}占优`; break; } } this.finish(winner, reason); }
  finish(winner, reason) { if (this.phase === "result") return; this.phase = "result"; this.cleanup(); this.ui.showResult(this, winner, reason); }
  cleanup() { for (const list of [this.units, this.buildings]) for (let i = list.length - 1; i >= 0; i--) if (list[i].dead) { this.renderer.destroyEntity(list[i]); list.splice(i, 1); } }
  city(side) { return this.buildings.find(b => b.side === side && b.type === "main_city"); }
  territory(side) { return [...this.tiles.values()].filter(t => t.revealed && t.owner === side).length; }
  unitTile(u) { const a = HexUtils.pixelToAxialRaw(u.x, u.y), p = HexUtils.round(a.q, a.r); return this.tile(p.q, p.r); }
  entityAxial(e) { return e.kind === "building" ? e.tile : HexUtils.pixelToAxialRaw(e.x, e.y); }
  distanceEntities(a, b) { const x = this.entityAxial(a), y = this.entityAxial(b); return HexUtils.distance(x.q, x.r, y.q, y.r); }
  distanceToTile(e, t) { const a = this.entityAxial(e); return HexUtils.distance(a.q, a.r, t.q, t.r); }
  canCapture(t, side) { return t.revealed && !t.building && t.owner !== side; }
}

// ===== Pixi 渲染 GameRenderer =====
class GameRenderer {
  constructor(app) { this.app = app; this.world = new PIXI.Container(); this.layers = {}; for (const n of ["map", "building", "unit", "health", "effect"]) { this.layers[n] = new PIXI.Container(); this.world.addChild(this.layers[n]); } app.stage.addChild(this.world); this.mapDirty = true; this.tileDisplays = new Map(); this.onBlank = null; app.stage.eventMode = "static"; app.stage.on("pointertap", () => this.onBlank?.()); window.addEventListener("resize", () => this.resize()); }
  reset() { for (const layer of Object.values(this.layers)) layer.removeChildren().forEach(c => c.destroy({ children: true })); this.tileDisplays.clear(); this.mapDirty = true; }
  buildMap(game) { for (const t of game.tiles.values()) { const c = new PIXI.Container(), g = new PIXI.Graphics(), label = new PIXI.Text("", { fontFamily: "Microsoft YaHei", fontSize: 18, fontWeight: "bold", fill: 0xffffff }); label.anchor.set(0.5); c.addChild(g, label); const p = HexUtils.axialToPixel(t.q, t.r); c.position.set(p.x, p.y); c.eventMode = "static"; c.cursor = "pointer"; c.hitArea = new PIXI.Polygon(Array.from({ length: 6 }, (_, i) => { const a = i * Math.PI / 3; return new PIXI.Point(HexUtils.size * Math.cos(a), HexUtils.size * Math.sin(a)); })); c.on("pointerover", () => c.scale.set(1.06)).on("pointerout", () => c.scale.set(1)).on("pointertap", e => { e.stopPropagation(); ui.onTile(t); }); this.layers.map.addChild(c); this.tileDisplays.set(key(t.q, t.r), { c, g, label }); } this.updateMap(game); }
  markMapDirty() { this.mapDirty = true; }
  update(game, dt) { if (this.mapDirty) this.updateMap(game); this.syncBuildings(game); this.syncUnits(game); this.updateEffects(dt); this.resize(); }
  updateMap(game) { const colors = CONFIG.map.colors; for (const t of game.tiles.values()) { const d = this.tileDisplays.get(key(t.q, t.r)); let fill = colors.unknownFill, line = colors.unknownLine, label = "?"; if (t.revealed) { fill = t.owner === "player" ? colors.playerFill : t.owner === "enemy" ? colors.enemyFill : colors.neutralFill; line = t.owner === "player" ? colors.playerLine : t.owner === "enemy" ? colors.enemyLine : colors.neutralLine; label = ""; } d.g.clear(); HexUtils.drawHex(d.g, HexUtils.size - 1, fill, line, 2); d.label.text = label; if (t.capture.progress > 0) { d.g.lineStyle(4, colors.captureLine); d.g.arc(0, 0, HexUtils.size - 5, -Math.PI / 2, -Math.PI / 2 + Math.PI * 2 * t.capture.progress / CONFIG.battle.captureTime); } } this.mapDirty = false; }
  syncBuildings(game) { for (const b of game.buildings) { if (b.dead) continue; if (!b.display) b.display = this.makeBuilding(b); const hp = b.display.hp; hp.clear(); this.drawHp(hp, b.hp / b.maxHp, 32, -29); } }
  // TODO: 替换为正式美术资源；当前建筑全部使用几何图形占位。
  makeBuilding(b) { const c = new PIXI.Container(), g = new PIXI.Graphics(); if (b.type === "gold_mine") g.beginFill(0xf2c14e).drawCircle(0, 0, 13).endFill(); else if (b.type.startsWith("barracks")) g.beginFill(0x567da3).lineStyle(2, 0xd6e7ef).drawRoundedRect(-15, -13, 30, 26, 4).endFill(); else if (b.type.startsWith("tower")) g.beginFill(b.type === "tower_cannon" ? 0xb76bb8 : 0x8c78c6).drawPolygon([-15, 13, 0, -17, 15, 13]).endFill(); else if (b.type === "general_camp") g.lineStyle(5, 0xe8b84e).drawCircle(0, 0, 15); else HexUtils.drawHex(g, 20, 0xd7a83c, 0xffe59a, 3); const short = b.type.includes("spear") ? "枪" : b.type.includes("cavalry") ? "骑" : b.type.includes("shield") ? "盾" : b.type.includes("archer") ? "弓" : b.type === "main_city" ? "城" : b.type === "general_camp" ? "将" : ""; if (short) { const tx = new PIXI.Text(short, { fontFamily: "Microsoft YaHei", fontSize: 13, fontWeight: "bold", fill: 0xffffff }); tx.anchor.set(0.5); c.addChild(tx); } const hp = new PIXI.Graphics(); c.addChildAt(g, 0); c.addChild(hp); const p = HexUtils.axialToPixel(b.tile.q, b.tile.r); c.position.set(p.x, p.y); this.layers.building.addChild(c); return { container: c, hp }; }
  syncUnits(game) { for (const u of game.units) { if (u.dead) continue; if (!u.display) u.display = this.makeUnit(u); u.display.container.position.set(u.x, u.y); const hp = u.display.hp; hp.clear(); if (u.hp < u.maxHp) this.drawHp(hp, u.hp / u.maxHp, u.isGeneral ? 26 : 18, u.isGeneral ? -23 : -15); } }
  // TODO: 替换为正式美术资源；当前士兵和武将使用圆形占位。
  makeUnit(u) { const c = new PIXI.Container(), g = new PIXI.Graphics(), color = u.isGeneral ? 0xe6b84f : CONFIG.units[u.type].color; g.beginFill(color).lineStyle(2, u.side === "player" ? 0x62e3a8 : 0xff6559).drawCircle(0, 0, u.isGeneral ? 11 : 7).endFill(); c.addChild(g); if (u.isGeneral) { g.lineStyle(2, 0xffdc73, 0.8).drawCircle(0, 0, 15); const tx = new PIXI.Text("关", { fontFamily: "Microsoft YaHei", fontSize: 10, fontWeight: "bold", fill: 0x3b2512 }); tx.anchor.set(0.5); c.addChild(tx); } const hp = new PIXI.Graphics(); c.addChild(hp); this.layers.unit.addChild(c); return { container: c, hp }; }
  drawHp(g, ratio, w, y) { g.beginFill(0x161616, 0.8).drawRect(-w / 2, y, w, 4).endFill(); g.beginFill(ratio > 0.5 ? 0x58c87c : ratio > 0.25 ? 0xe4bd45 : 0xdb4d43).drawRect(-w / 2, y, w * clamp(ratio, 0, 1), 4).endFill(); }
  destroyEntity(e) { if (e.display) { e.display.container.destroy({ children: true }); e.display = null; } }
  effectLine(a, b, color) { const pa = a.q != null ? HexUtils.axialToPixel(a.q, a.r) : { x: a.x, y: a.y }, pb = b.kind === "building" ? HexUtils.axialToPixel(b.tile.q, b.tile.r) : { x: b.x, y: b.y }, g = new PIXI.Graphics(); g.lineStyle(3, color, 0.85).moveTo(pa.x, pa.y).lineTo(pb.x, pb.y); g.life = 0.12; this.layers.effect.addChild(g); }
  effectRing(x, y, range, color) { const g = new PIXI.Graphics(); g.lineStyle(4, color, 0.8).drawCircle(x, y, range * Math.sqrt(3) * HexUtils.size); g.life = 0.25; this.layers.effect.addChild(g); }
  updateEffects(dt) { for (const g of [...this.layers.effect.children]) { g.life -= dt; g.alpha = clamp(g.life * 5, 0, 1); if (g.life <= 0) { this.layers.effect.removeChild(g); g.destroy(); } } }
  resize() { this.app.stage.hitArea = this.app.screen; if (!this.tileDisplays.size) return; const viewport = CONFIG.map.viewport, pts = [...this.tileDisplays.values()].map(d => d.c.position), minX = Math.min(...pts.map(p => p.x)) - HexUtils.size, maxX = Math.max(...pts.map(p => p.x)) + HexUtils.size, minY = Math.min(...pts.map(p => p.y)) - HexUtils.size, maxY = Math.max(...pts.map(p => p.y)) + HexUtils.size, availW = this.app.screen.width - viewport.padding * 2, availH = Math.max(viewport.minHeight, this.app.screen.height - viewport.reservedTop - viewport.reservedBottom), scale = Math.min(viewport.maxScale, availW / (maxX - minX), availH / (maxY - minY)); this.world.scale.set(scale); this.world.pivot.set((minX + maxX) / 2, (minY + maxY) / 2); this.world.position.set(this.app.screen.width / 2, viewport.reservedTop + availH / 2); }
}

// ===== DOM UI UIController =====
class UIController {
  constructor() { this.el = { timer: document.querySelector("#timer"), prepare: document.querySelector("#prepare-overlay"), prepareCount: document.querySelector("#prepare-count"), menu: document.querySelector("#build-menu"), grid: document.querySelector("#build-grid"), title: document.querySelector("#selection-title"), hint: document.querySelector("#hint"), toast: document.querySelector("#toast"), result: document.querySelector("#result-panel"), mapSelect: document.querySelector("#map-select"), mapGrid: document.querySelector("#map-grid"), mapClose: document.querySelector("#map-close") }; this.toastTimer = null; this.mapResumePhase = null; document.querySelector("#close-build").onclick = () => this.closeBuild(); document.querySelector("#restart-btn").onclick = () => { if (confirm("确定重新开始本局？")) game.reset(); }; document.querySelector("#again-btn").onclick = () => game.reset(); document.querySelector("#map-select-btn").onclick = () => this.openMapSelect(true); this.el.mapClose.onclick = () => this.closeMapSelect(); document.addEventListener("keydown", e => { if (e.key === "Escape") { this.closeBuild(); if (this.mapResumePhase) this.closeMapSelect(); } }); }
  reset() { this.closeBuild(); this.el.result.classList.remove("show"); this.el.prepare.classList.add("show"); this.el.title.textContent = "大王请留步"; this.el.hint.textContent = "准备开战：翻格扩张，建营出兵，攻破敌城。"; }
  update(game) { const sec = Math.ceil(game.timeLeft); this.el.timer.textContent = game.phase === "menu" ? "选地图" : game.phase === "prepare" ? "准备" : `${String(Math.floor(sec / 60)).padStart(2, "0")}:${String(sec % 60).padStart(2, "0")}`; this.el.prepare.classList.toggle("show", game.phase === "prepare"); this.el.prepareCount.textContent = Math.max(1, Math.ceil(game.prepareLeft)); for (const side of SIDES) { document.querySelector(`#${side}-gold`).textContent = Math.floor(game.sides[side].gold); document.querySelector(`#${side}-land`).textContent = game.territory(side); document.querySelector(`#${side}-city`).textContent = Math.ceil(game.city(side)?.hp || 0); } }
  onTile(tile) { game.selectedTile = tile; const b = tile.building; this.el.title.textContent = b ? `${b.name} · ${tile.owner === "player" ? "我方" : tile.owner === "enemy" ? "敌方" : "中立"}` : `地块 (${tile.q}, ${tile.r})`; if (game.phase !== "battle") { this.el.hint.textContent = "准备阶段暂不可操作"; return; } if (!tile.revealed) { const legal = HexUtils.neighbors(tile.q, tile.r).some(p => game.tile(p.q, p.r)?.owner === "player"); this.el.hint.textContent = legal ? `点击翻格，消耗 ${CONFIG.reveal.normalCost} 金币` : "只能翻开与我方领地相邻的地块"; if (!legal) this.toast("该地块不与我方领地相邻"); else if (game.sides.player.gold < CONFIG.reveal.normalCost) this.toast("金币不足"); else game.reveal(tile, "player"); return; } if (b) { this.el.hint.textContent = `生命 ${Math.ceil(b.hp)}/${b.maxHp} · ${this.describeBuilding(b.type)}`; return; } if (tile.owner === "player") { this.el.hint.textContent = "选择要建造的建筑"; this.openBuild(tile); } else this.el.hint.textContent = tile.owner === "enemy" ? "敌方空地，可由士兵占领" : "中立空地，可由士兵占领"; }
  describeBuilding(type) { const c = CONFIG.buildings[type]; if (type === "gold_mine") return `+${c.income} 金/秒`; if (type.startsWith("barracks")) return `每 ${c.spawnInterval} 秒出兵`; if (type.startsWith("tower")) return `伤害 ${c.atk} · 范围 ${c.range}`; if (type === "main_city") return "生命归零则失败"; return "召唤并复活关羽"; }
  openBuild(tile) { this.el.grid.innerHTML = ""; for (const type of BUILDABLE) { const c = CONFIG.buildings[type], btn = document.createElement("button"); btn.className = "build-option"; btn.disabled = game.sides.player.gold < c.cost; btn.innerHTML = `${c.name}<small>${c.cost} 金 · ${c.hp} 生命</small>`; btn.onclick = () => { if (game.build(tile, type, "player")) { this.toast(`建造${c.name}`); this.closeBuild(); } else this.toast("无法建造"); }; this.el.grid.appendChild(btn); } this.el.menu.classList.add("open"); const w = 330, x = clamp(innerWidth / 2 - w / 2, 10, innerWidth - w - 10), y = clamp(innerHeight / 2 - 150, 76, innerHeight - 390); this.el.menu.style.left = `${x}px`; this.el.menu.style.top = `${y}px`; }
  closeBuild() { this.el.menu.classList.remove("open"); }
  openMapSelect(canClose) { this.closeBuild(); this.mapResumePhase = canClose ? game.phase : null; game.phase = "menu"; this.el.mapClose.classList.toggle("show", canClose); this.renderMapChoices(); this.el.mapSelect.classList.add("show"); }
  closeMapSelect() { if (!this.mapResumePhase) return; game.phase = this.mapResumePhase; this.mapResumePhase = null; this.el.mapSelect.classList.remove("show"); }
  renderMapChoices() { this.el.mapGrid.innerHTML = ""; for (const map of Object.values(CONFIG.maps)) { const card = document.createElement("button"); card.className = `map-card${map.id === game.currentMapId ? " active" : ""}`; card.style.setProperty("--map-a", this.colorHex(map.colors.playerFill)); card.style.setProperty("--map-b", this.colorHex(map.colors.enemyFill)); const shapeName = map.shape === "offsetRectangle" ? "长方形轮廓" : "斜向轮廓"; card.innerHTML = `<h2>${map.name}</h2><p>${map.description}</p><div class="map-meta"><span>${map.cols} × ${map.rows}</span><span>${shapeName}</span><span>${map.hexSize}px</span></div>`; card.onclick = () => { game.selectMap(map.id); this.mapResumePhase = null; this.el.mapSelect.classList.remove("show"); this.toast(`进入${map.name}`); }; this.el.mapGrid.appendChild(card); } }
  colorHex(value) { return `#${value.toString(16).padStart(6, "0")}`; }
  toast(text) { clearTimeout(this.toastTimer); this.el.toast.textContent = text; this.el.toast.classList.add("show"); this.toastTimer = setTimeout(() => this.el.toast.classList.remove("show"), 1500); }
  showResult(game, winner, reason) { this.closeBuild(); this.el.result.classList.add("show"); document.querySelector("#result-title").textContent = winner === "player" ? "胜利！" : winner === "enemy" ? "失败" : "平局"; document.querySelector("#result-reason").textContent = reason; const rows = [["击杀单位", "unitKills"], ["摧毁建筑", "buildingsDestroyed"], ["成功占领", "captures"], ["当前领地", null], ["总产金币", "goldEarned"]]; document.querySelector("#stats-body").innerHTML = rows.map(([label, k]) => `<tr><td>${label}</td><td>${Math.floor(k ? game.sides.player[k] : game.territory("player"))}</td><td>${Math.floor(k ? game.sides.enemy[k] : game.territory("enemy"))}</td></tr>`).join(""); }
}

// ===== 初始化 =====
function validateMapConfig(map, mapId = map.id || "unknown") {
  if (!Number.isInteger(map.cols) || map.cols < 2 || !Number.isInteger(map.rows) || map.rows < 2) {
    throw new Error(`地图 ${mapId} 的 cols 和 rows 必须是大于等于 2 的整数`);
  }
  if (!Number.isFinite(map.hexSize) || map.hexSize <= 0) throw new Error(`地图 ${mapId} 的 hexSize 必须大于 0`);
  if (!["axialParallelogram", "offsetRectangle"].includes(map.shape)) throw new Error(`地图 ${mapId} 使用了未知 shape：${map.shape}`);
  const layout = map.initialLayout;
  const validCells = new Set(getMapCoordinates(map).map(p => key(p.q, p.r)));
  const positions = [
    ["playerCity", layout.playerCity],
    ...layout.playerTerritory.map((p, i) => [`playerTerritory[${i}]`, p]),
    ["enemyCity", layout.enemyCity],
    ...layout.enemyTerritory.map((p, i) => [`enemyTerritory[${i}]`, p]),
  ];
  const occupied = new Set();
  for (const [name, p] of positions) {
    if (!Number.isInteger(p?.q) || !Number.isInteger(p?.r) || !validCells.has(key(p.q, p.r))) {
      throw new Error(`地图 ${mapId} 初始坐标 ${name} (${p?.q}, ${p?.r}) 不在有效地块内`);
    }
    const positionKey = key(p.q, p.r);
    if (occupied.has(positionKey)) throw new Error(`地图 ${mapId} 初始坐标重复：${name} 位于 ${positionKey}`);
    occupied.add(positionKey);
  }
  const viewport = map.viewport;
  if (viewport.padding < 0 || viewport.reservedTop < 0 || viewport.reservedBottom < 0 || viewport.minHeight <= 0 || viewport.maxScale <= 0) {
    throw new Error(`地图 ${mapId} 的 viewport 配置无效`);
  }
}

for (const [mapId, map] of Object.entries(CONFIG.maps)) validateMapConfig(map, mapId);
const probabilitySum = Object.values(CONFIG.revealRates.normal).reduce((a, b) => a + b, 0);
if (Math.abs(probabilitySum - 1) > 1e-6) throw new Error(`普通翻格概率之和必须为 1，当前为 ${probabilitySum}`);
if (!window.PIXI) throw new Error("PixiJS 加载失败，请检查网络连接");
const app = new PIXI.Application({ resizeTo: window, backgroundAlpha: 0, antialias: true, autoDensity: true, resolution: Math.min(devicePixelRatio || 1, 2) });
document.querySelector("#game-container").appendChild(app.view);
const renderer = new GameRenderer(app), ui = new UIController();
renderer.onBlank = () => ui.closeBuild();
let game = new Game(renderer, ui);
ui.openMapSelect(false);
app.ticker.add(() => { const dt = Math.min(app.ticker.deltaMS / 1000, 0.1); game.update(dt); renderer.update(game, dt); ui.update(game); });
